# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5308d1cb006a24ad5e4319aef3a55a80122cfa8e252fa2e5e08e6b3a882356cb66759ae39951fbe4ea9be7d0802d5b9452149f8e4fd92d6f33c7d20d95135bf8

test:
  secret_key_base: 7da6fd203eca1dafa5b89ff85a7ecb6ad08c32cbb3cc163203826e93de2c4171abb5d6f4109ee39b8d0b2e61e43cb8b2ddcd1a774402eb9d44ad6d3355f77b72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
